---
output: github_document
title: "Group Work in the Lexicography Class for the Holle List of the Barrier Islands Languages of Indonesia"
author: "Gede Primahadi W. Rajeg & I Wayan Arka"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- badges: start -->
<!-- badges: end -->

## How to cite

*forthcoming*

## Overview

*forthcoming*

## Student contributors

Name | Language File | Description | Role
--- | --- | --- | ---
Suari, Ni Kadek Maritya | Nias 1905 | List Number 1-514; Notes Number 1-29 |
Dinahari, Diorani Risky | Nias 1905 | List Number 516-1031; Notes Number 30-58 |
Bakti, Three Anggano Putra | Nias 1905 | List Number 1032-1546; Notes Number 59-87 |
Dewani, Ade Galuh Cahya | Nias 1911 | List Number 1-514; Notes Number 1-38 |
Dabukke, Mary Deliana Esther | Nias 1911 | List Number 515-1021; Notes Number 39-71 |
Ellena, Natasya R. | Nias 1911 | List Number 1022-1546; Notes Number 72-121 |
Ramawan, Kadek Gilang | Salang & Sigulè | List Number 1-420; Notes Number 1-35; shared equally for List Number 1304-1486 |
Mahasari, I Gusti Ayu Mirah | Salang & Sigulè | List Number 421-878; Notes Number 36-70; shared equally for List Number 1304-1486 |
Nismara, I Pande Putu Kenzie Arvan | Salang & Sigulè | List Number 881-1303; Notes Number 71-107; shared equally for List Number 1304-1486 |

... more to come

